// Code generated by underscore_generate. DO NOT EDIT.

package stack

import (
	"fmt"
	"strings"
)

type Complex64Stack interface {
	fmt.Stringer

	Push(i complex64)
	Pop() complex64
	Peek() complex64
	Len() int
	IsEmpty() bool
	Clone() Complex64Stack
}

func NewComplex64() Complex64Stack {
	return &complex64Stack{}
}

var _ Complex64Stack = (*complex64Stack)(nil)

type complex64Stack struct {
	is []complex64
}

func (s *complex64Stack) String() string {
	var buf = new(strings.Builder)
	for i, v := range s.is {
		if i == 0 {
			buf.WriteString(fmt.Sprintf("%v", v))
		} else {
			buf.WriteString(fmt.Sprintf(" < %v", v))
		}
	}
	return buf.String()
}

func (s *complex64Stack) Push(i complex64) {
	s.is = append(s.is, i)
}

func (s *complex64Stack) Pop() complex64 {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	p := s.Peek()
	s.is = s.is[:len(s.is)-1]
	return p
}

func (s *complex64Stack) Peek() complex64 {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	return s.is[len(s.is)-1]
}

func (s *complex64Stack) Len() int {
	return len(s.is)
}

func (s *complex64Stack) IsEmpty() bool {
	return len(s.is) == 0
}

func (s *complex64Stack) Clone() Complex64Stack {
	s2 := &complex64Stack{is: make([]complex64, 0, len(s.is))}
	for _, v := range s.is {
		s2.is = append(s2.is, v)
	}
	return s2
}
