// Code generated by underscore_generate. DO NOT EDIT.

package stack

import (
	"fmt"
	"strings"
)

type Float64Stack interface {
	fmt.Stringer

	Push(i float64)
	Pop() float64
	Peek() float64
	Len() int
	IsEmpty() bool
	Clone() Float64Stack
}

func NewFloat64() Float64Stack {
	return &float64Stack{}
}

var _ Float64Stack = (*float64Stack)(nil)

type float64Stack struct {
	is []float64
}

func (s *float64Stack) String() string {
	var buf = new(strings.Builder)
	for i, v := range s.is {
		if i == 0 {
			buf.WriteString(fmt.Sprintf("%v", v))
		} else {
			buf.WriteString(fmt.Sprintf(" < %v", v))
		}
	}
	return buf.String()
}

func (s *float64Stack) Push(i float64) {
	s.is = append(s.is, i)
}

func (s *float64Stack) Pop() float64 {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	p := s.Peek()
	s.is = s.is[:len(s.is)-1]
	return p
}

func (s *float64Stack) Peek() float64 {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	return s.is[len(s.is)-1]
}

func (s *float64Stack) Len() int {
	return len(s.is)
}

func (s *float64Stack) IsEmpty() bool {
	return len(s.is) == 0
}

func (s *float64Stack) Clone() Float64Stack {
	s2 := &float64Stack{is: make([]float64, 0, len(s.is))}
	for _, v := range s.is {
		s2.is = append(s2.is, v)
	}
	return s2
}
