// Code generated by underscore_generate. DO NOT EDIT.

package stack

import (
	"fmt"
	"strings"
)

type RuneStack interface {
	fmt.Stringer

	Push(i rune)
	Pop() rune
	Peek() rune
	Len() int
	IsEmpty() bool
	Clone() RuneStack
}

func NewRune() RuneStack {
	return &runeStack{}
}

var _ RuneStack = (*runeStack)(nil)

type runeStack struct {
	is []rune
}

func (s *runeStack) String() string {
	var buf = new(strings.Builder)
	for i, v := range s.is {
		if i == 0 {
			buf.WriteString(fmt.Sprintf("%v", v))
		} else {
			buf.WriteString(fmt.Sprintf(" < %v", v))
		}
	}
	return buf.String()
}

func (s *runeStack) Push(i rune) {
	s.is = append(s.is, i)
}

func (s *runeStack) Pop() rune {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	p := s.Peek()
	s.is = s.is[:len(s.is)-1]
	return p
}

func (s *runeStack) Peek() rune {
	if s.IsEmpty() {
		panic("stack is empty")
	}
	return s.is[len(s.is)-1]
}

func (s *runeStack) Len() int {
	return len(s.is)
}

func (s *runeStack) IsEmpty() bool {
	return len(s.is) == 0
}

func (s *runeStack) Clone() RuneStack {
	s2 := &runeStack{is: make([]rune, 0, len(s.is))}
	for _, v := range s.is {
		s2.is = append(s2.is, v)
	}
	return s2
}
